### ISSUE TITLE
Cannot sort or filter dynamic column

### ISSUE THREAD

**Issue by anotherdeveloper** [IvanJosipovic/BlazorTable#91]
Using this code

```
<button class="btn btn-sm btn-danger" title="Add Column" @onclick="@((x) => Add())">Add Column</button>

<br />
<Table  TableItem="Item" Items="data" PageSize="5" @ref="Table" ColumnReorder="true">
    <Column TableItem="Item" Title="Id" Field="@(x => x.Id)" Sortable="true" Filterable="true" />
    <Pager ShowPageNumber="true" ShowTotalCount="true" />
</Table>

@code
{
    private ITable<Item> Table;

    private IEnumerable<Item> data;

    protected override Task OnInitializedAsync()
    {
        data = new Item[]{
            new Item {Id=12,Value=876   },
            new Item {Id=13, Value=188   },
            new Item {Id=14, Value=6688   },
            new Item {Id=15,Value=884   },
            new Item {Id=16,Value=1234   },
            new Item {Id=17,Value=838   },
            new Item {Id=18,Value=288   },
            new Item {Id=19,Value=188   }

        };
        return Task.CompletedTask;
    }

    public class Item
    {
        public int Id { get; set; }

        public decimal Value { get; set; }
    }

    private void Add()
    {
        var col = new Column<Item>()
        {
            Title = "Value",
            Field = (x) => x.Value,
            Sortable = true,
            Filterable = true,
            Width = "10%"
            , SortColumn=true
        };

        Table.AddColumn(col);
    }
}
```
Filtering on the new column gives me
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlazorTable.Column`1.ToggleFilter()
   at BlazorTable.Table`1.<>c__DisplayClass102_0.<BuildRenderTree>b__4(MouseEventArgs x)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '53evlbBFkNyGDLRCtfH067Ajr3k1Qo-Gcjsx3f1vFqk'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlazorTable.Column`1.ToggleFilter()
   at BlazorTable.Table`1.<>c__DisplayClass102_0.<BuildRenderTree>b__4(MouseEventArgs x)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```
and sorting on the new column gives me
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlazorTable.Column`1.SortBy()
   at BlazorTable.Table`1.<>c__DisplayClass102_0.<BuildRenderTree>b__3()
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
```
How can I filter and sort without exceptions?

**Comment by IvanJosipovic** [comment]
Hey, 

I am looking into this. For now, if you set the Table parameter in the Column object, this will get sorting working.
I am looking into why filtering isn't working, this will likely require a code change from my end.

```
    private void Add()
    {
        var col = new Column<Item>()
        {
            Table = Table, // Add This
            Title = "Value",
            Field = (x) => x.Value,
            Sortable = true,
            Filterable = true,
            Width = "10%",
            SortColumn=true
        };

        Table.AddColumn(col);
    }
```

**Comment by anotherdeveloper** [comment]
Great, thanks.

**Comment by IvanJosipovic** [comment]
I just pushed release [1.5.1](https://github.com/IvanJosipovic/BlazorTable/releases/tag/v1.5.1), it should be on visible on NuGet in the next 15 mins.

You can test the fix here https://blazortable.netlify.com/AddColumn
